spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Rework?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        default_batch_fetch_size: 1000
      defer-datasource-initialization: true
      show-sql: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #  redis configuration
  data:
    redis:
      port: 6379
      host: localhost


jwt:
  secret-key: mobile_app_1234567890

