name: Java CI with Gradle

# 동작 조건 설정 : develop 브랜치에 push 혹은 pull request가 발생할 경우 동작한다.
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # 1. Java 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 2. Spring Boot 애플리케이션 빌드
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar

    # 3. Docker 이미지 태그 설정
    - name: Set Docker Image Tag
      id: docker_tag
      run: echo "DOCKER_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/rework-backend:${{ github.run_number }}" >> $GITHUB_ENV

    # 4. Docker 이미지 빌드
    - name: docker image build
      run: docker build -t ${{ env.DOCKER_IMAGE_TAG }} .

    # 5. DockerHub 로그인
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 6. Docker Hub 이미지 푸시
    - name: docker Hub push
      run: docker push ${{ env.DOCKER_IMAGE_TAG }}

    # 7. 서버에 접속하여 스크립트 실행
    - name: Deploy to Prod Server
      uses: appleboy/ssh-action@v1.0.3
      if: contains(github.ref, 'develop')
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key: ${{ secrets.MAIN_SSH_KEY }}
        port: 22
        script: |
          cd rework && sed -i "s/^BUILD_NUMBER=.*/BUILD_NUMBER=${{ github.run_number }}/" .env && ./deploy.sh
  
  send-discord-notification:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: ${{ github.run_number }} "번째 프로젝트가 정상적으로 배포되었습니다!"
