name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar

    - name: Set Docker Image Tag
      id: docker_tag
      run: echo "DOCKER_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/rework-backend:${{ github.run_number }}" >> $GITHUB_ENV

    - name: Set Build Number
      run: |
        echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        echo "BUILD_NUMBER=${{ github.run_number }}" > .env

    - name: docker image build
      run: docker build -t ${{ env.DOCKER_IMAGE_TAG }} .

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ env.DOCKER_IMAGE_TAG }}

    - name: Deploy to Prod Server
      uses: appleboy/ssh-action@v1.0.3
      if: contains(github.ref, 'develop')
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key: ${{ secrets.MAIN_SSH_KEY }}
        port: 22
        script: |
          cd rework && ./deploy.sh
